language: groovy
jdk:
  - oraclejdk7
branches:
  only:
    - master
script:
  - ./grailsw refresh-dependencies
  - ./grailsw test-app -echoOut -echoErr -coverage -xml
after_success:
  - ./grailsw coveralls
cache:
  directories:
  - $HOME/.m2
  - $HOME/.npm
