env:
  - NODE_VERSION=0.11

install:
  - nvm install $NODE_VERSION
  - node --version
  - npm --version
  - git --version
  - svn --version | head -n 1
  - npm install -g grunt-cli
  - npm install

language: groovy

jdk:
  - oraclejdk7

branches:
  only:
    - master

script:
  - ./grailsw refresh-dependencies
  - ./grailsw test-app -echoOut -echoErr -coverage -xml

after_success:
  - ./grailsw coveralls

cache:
  directories:
  - $HOME/.m2
  - $HOME/.npm
  - $HOME/.nvm
