env:
  - NODE_VERSION=0.11

install:
  #Installations for front-end dependencies
  - nvm install $NODE_VERSION
  - node --version
  - npm --version
  - git --version
  - npm install

language: groovy

jdk:
  - oraclejdk7

branches:
  only:
    - master

script:
  - ./grailsw refresh-dependencies
  - ./grailsw test-app -echoOut -echoErr -coverage -xml
  - karma start grails-app/conf/karma.conf.js --no-auto-watch --single-run --browsers PhantomJS --log-level debug

after_success:
  - ./grailsw coveralls

cache:
  directories:
  - $HOME/.m2
  - $HOME/.npm
  - $HOME/.nvm
  - $HOME/.cache/bower/
